version: '3'

services:
  mysqldb:
    image: mysql:8.0.2
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: customersdb
    ports:
      - "3307:3306"
    volumes:
      - ./database:/docker-entrypoint-initdb.d
   
  app:
    build: .
    depends_on:
      - mysqldb
    links:
      - mysqldb
    ports:
      - 3000:3000
    volumes:
      - .:/myapp

